import { ApprovalRecordSchema } from "../schemas/approval-record.js";
import { DesignIntakeSchema, type DesignIntake } from "../schemas/intake.js";
import { SCHEMA_VERSION } from "../schemas/version.js";

export const PILOT_NOW = "2026-09-08T04:00:00.000Z";
export const PILOT_ID = "pilot-m1-studio-north";
export const PILOT_JOB_ID = "job_pilot_m1_studio_north";

export function buildPilotApprovals(now = PILOT_NOW) {
  return [
    ApprovalRecordSchema.parse({
      schemaVersion: SCHEMA_VERSION,
      id: "apr-copy-pilot",
      createdAt: now,
      updatedAt: now,
      subject: "copy",
      subjectId: "copy-pilot-1",
      status: "approved",
      approvedBy: "operator@studionorth.example",
      approvedAt: now,
      notes: ["Locked for M1 pilot"],
    }),
    ApprovalRecordSchema.parse({
      schemaVersion: SCHEMA_VERSION,
      id: "apr-brief-pilot",
      createdAt: now,
      updatedAt: now,
      subject: "brief",
      subjectId: "intake-pilot-1",
      status: "approved",
      approvedBy: "operator@studionorth.example",
      approvedAt: now,
      notes: [],
    }),
    ApprovalRecordSchema.parse({
      schemaVersion: SCHEMA_VERSION,
      id: "apr-brand-pilot",
      createdAt: now,
      updatedAt: now,
      subject: "brand",
      subjectId: "brand-studio-north",
      status: "approved",
      approvedBy: "brand@studionorth.example",
      approvedAt: now,
      notes: [],
    }),
    ApprovalRecordSchema.parse({
      schemaVersion: SCHEMA_VERSION,
      id: "apr-logo-pilot",
      createdAt: now,
      updatedAt: now,
      subject: "logo",
      subjectId: "asset-logo-1",
      status: "approved",
      approvedBy: "brand@studionorth.example",
      approvedAt: now,
      notes: [],
    }),
    ApprovalRecordSchema.parse({
      schemaVersion: SCHEMA_VERSION,
      id: "apr-price-pilot",
      createdAt: now,
      updatedAt: now,
      subject: "price",
      subjectId: "claim-price-1",
      status: "approved",
      approvedBy: "ops@studionorth.example",
      approvedAt: now,
      notes: [],
    }),
    ApprovalRecordSchema.parse({
      schemaVersion: SCHEMA_VERSION,
      id: "apr-contact-pilot",
      createdAt: now,
      updatedAt: now,
      subject: "contact",
      subjectId: "claim-phone-1",
      status: "approved",
      approvedBy: "ops@studionorth.example",
      approvedAt: now,
      notes: [],
    }),
    ApprovalRecordSchema.parse({
      schemaVersion: SCHEMA_VERSION,
      id: "apr-date-pilot",
      createdAt: now,
      updatedAt: now,
      subject: "date",
      subjectId: "claim-date-1",
      status: "approved",
      approvedBy: "ops@studionorth.example",
      approvedAt: now,
      notes: [],
    }),
  ];
}

/** Approved intake for Studio North Open Studio Night — poster + business card. */
export function buildPilotIntake(now = PILOT_NOW): DesignIntake {
  return DesignIntakeSchema.parse({
    schemaVersion: SCHEMA_VERSION,
    id: "intake-pilot-1",
    createdAt: now,
    updatedAt: now,
    organizationName: "Studio North",
    title: "Open Studio Night",
    offer: "An evening of live demos and new work from resident makers",
    whoNeedsIt: {
      primaryAudience: "Local creatives and collectors",
      secondaryAudience: "Neighbors curious about the studio",
      demographicsNotes: ["Adults 25–55 in the warehouse district"],
      psychographicsNotes: ["Prefer low-pressure visits over ticketed openings"],
    },
    purchaseTrigger: {
      situation: "Looking for a low-friction way to visit the studio this week",
      stage: "solution_aware",
      objections: ["Worried it will feel like a hard sell"],
      competitors: ["Downtown gallery crawl promos"],
    },
    twoSecondUnderstanding: "Studio North is open Friday — come see new work",
    nextAction: "RSVP today",
    copyAndClaims: {
      approvedCopy: {
        schemaVersion: SCHEMA_VERSION,
        id: "copy-pilot-1",
        createdAt: now,
        updatedAt: now,
        headline: "Open Studio Night",
        subhead: "See the work. Meet the makers.",
        body: "Friday 6–9pm. Free entry. Live demos on the floor.",
        callToAction: "RSVP today",
        lockedLines: {
          dateLine: "Friday 6–9pm",
          placeLine: "Studio North · Warehouse District",
        },
        claims: [
          {
            id: "claim-price-1",
            kind: "price",
            text: "Free entry",
            sourceLabel: "Event brief v3",
            approvalRecordId: "apr-price-pilot",
          },
          {
            id: "claim-phone-1",
            kind: "contact",
            text: "+1 555 0100",
            sourceLabel: "CRM primary phone",
            approvalRecordId: "apr-contact-pilot",
          },
          {
            id: "claim-date-1",
            kind: "date",
            text: "Friday 6–9pm",
            sourceLabel: "Event calendar",
            approvalRecordId: "apr-date-pilot",
          },
        ],
        approvalRecordId: "apr-copy-pilot",
        approvalStatus: "approved",
      },
      prohibitedClaims: [
        "best gallery in the world",
        "guaranteed collector sales",
        "limited spots almost gone",
      ],
      supportedClaims: [],
    },
    brandAssets: {
      brandName: "Studio North",
      brandApprovalRecordId: "apr-brand-pilot",
      voice: {
        tone: ["polished", "confident", "human", "clear", "sales-focused"],
        doSay: ["See the work", "Meet the makers", "RSVP today"],
        dontSay: ["revolutionary", "world-class", "guaranteed results"],
        banHype: true,
        neverInventFacts: true,
      },
      colors: [
        { role: "primary", hex: "#1A1A1A", name: "Ink" },
        { role: "secondary", hex: "#E8E2D6", name: "Paper" },
        { role: "accent", hex: "#C45C26", name: "Kiln" },
        {
          role: "other",
          hex: "#8B3416",
          name: "Kiln CTA fill (print-safe with white text)",
        },
      ],
      fonts: [
        {
          role: "headline",
          family: "Freight Display",
          fallbackStack: ["Georgia", "serif"],
          licensed: true,
        },
        {
          role: "body",
          family: "Söhne",
          fallbackStack: ["Helvetica Neue", "sans-serif"],
          licensed: true,
        },
      ],
      logos: [
        {
          assetId: "asset-logo-1",
          approvalRecordId: "apr-logo-pilot",
          usage: "primary",
        },
      ],
      logoRules: {
        primaryAssetId: "asset-logo-1",
        minClearSpace: { value: 0.25, unit: "in" },
        allowedBackgrounds: ["white", "#E8E2D6"],
        forbiddenTreatments: ["stretch", "recolor_off_brand", "add_effects"],
        mustRemainIntact: true,
      },
      imageStyle: {
        description: "Real studio spaces, natural light, work in progress",
        subjectMatter: ["workbenches", "tools", "open doorway"],
        doPrefer: ["Documentary framing", "Warm dusk light"],
        doAvoid: ["Stock handshakes", "Neon nightlife tropes"],
      },
      assets: [
        {
          assetId: "asset-logo-1",
          label: "Primary mark",
          kind: "logo",
          classes: ["fixed", "approval_required", "distinctive"],
          permittedVariation: [],
          licenseRecordId: "lic-logo-1",
          approvalRecordId: "apr-logo-pilot",
          localPath: "brand/logo.svg",
        },
      ],
      licenseRecords: [
        {
          id: "lic-logo-1",
          assetId: "asset-logo-1",
          owner: "Studio North",
          licenseType: "owned",
          licenseLabel: "In-house mark",
          commercialUseAllowed: true,
          modificationAllowed: false,
          attributionRequired: false,
          notes: [],
        },
      ],
      distinctivenessAudit: {
        schemaVersion: SCHEMA_VERSION,
        id: "da-pilot-1",
        createdAt: now,
        updatedAt: now,
        brandId: "intake-pilot-1-brand",
        brandName: "Studio North",
        audienceSummary: "Local creatives and collectors",
        findings: [
          {
            assetId: "asset-logo-1",
            assetLabel: "Primary mark",
            recognitionHypothesis: {
              statement:
                "Viewers will recognize the mark from neighborhood signage",
              believedRecognized: true,
              confidence: "medium",
              evidenceStatus: "hypothesis",
              evidenceNotes: [
                "Unverified — pilot will run recognition question",
              ],
            },
            uniqueAssociationHypothesis: {
              statement:
                "Viewers will link the mark to Studio North, not a generic atelier",
              believedUniqueToBrand: true,
              confidence: "low",
              evidenceStatus: "hypothesis",
              evidenceNotes: [],
              confusionRisks: ["Generic craft-studio monograms"],
            },
            productionRecommendation: "test_before_scale",
          },
        ],
        overallNotes: ["Distinctiveness remains hypothesis until human test"],
      },
    },
    outputs: [
      {
        formatId: "poster",
        channel: "print_poster",
        label: "Open Studio Night poster",
        hardConstraints: {
          mustIncludeText: [
            "Open Studio Night",
            "RSVP today",
            "Studio North",
            "Friday 6–9pm",
            "Free entry",
          ],
          mustExcludeText: [],
          formatId: "poster",
          dimensions: { width: 18, height: 24, unit: "in" },
          localization: { locale: "en-US", language: "en", rtl: false },
          accessibility: {
            minContrastRatio: 4.5,
            altTextRequired: true,
            colorBlindSafe: false,
            notes: ["Reading distance ~4–6 ft"],
          },
          printer: {
            required: true,
            bleedInches: 0.125,
            safeMarginInches: 0.5,
            colorMode: "cmyk",
            notes: ["Poster stock, matte"],
          },
          requireApprovalFor: [
            "copy",
            "price",
            "date",
            "testimonial",
            "logo",
            "certification",
            "contact",
            "claim",
          ],
        },
      },
      {
        formatId: "business_card",
        channel: "print_business_card",
        label: "Open Studio Night handout card",
        hardConstraints: {
          mustIncludeText: [
            "Open Studio Night",
            "RSVP today",
            "Studio North",
            "+1 555 0100",
          ],
          mustExcludeText: [],
          formatId: "business_card",
          dimensions: { width: 3.5, height: 2, unit: "in" },
          localization: { locale: "en-US", language: "en", rtl: false },
          accessibility: {
            minContrastRatio: 4.5,
            altTextRequired: true,
            colorBlindSafe: false,
            notes: ["Hand-held reading"],
          },
          printer: {
            required: true,
            bleedInches: 0.125,
            safeMarginInches: 0.125,
            colorMode: "cmyk",
            notes: ["16pt soft-touch"],
          },
          requireApprovalFor: [
            "copy",
            "price",
            "date",
            "testimonial",
            "logo",
            "certification",
            "contact",
            "claim",
          ],
        },
      },
    ],
    creativePreferences: {
      moodKeywords: ["inviting", "documentary", "warm"],
      visualStyle: "Open doorway at dusk with quiet type",
      preferredPaletteHints: ["#1A1A1A", "#E8E2D6", "#C45C26"],
      typographyHints: ["Strong headline, restrained support"],
      imageryHints: ["Lit studio doorway"],
      doPrefer: ["One message, one CTA"],
      doAvoid: ["Schedule grids", "Badge clusters", "QR in bleed"],
      referenceUrls: [],
      notes: ["M1 pilot: poster + business card only"],
    },
    briefApprovalRecordId: "apr-brief-pilot",
  });
}
